language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn test

notifications:
  email:
    recipients:
      - fel772@hotmail.com
      - oscar@arepa.dev
    on_success: always
    on_failure: always

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: 1390e29e-4f08-439e-a84d-c3cad3301b6a
  app: platzi-store-backend3
  on:
    repo: l33pif/platzi-store-backend
